mysite/allauth/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'allauth'
urlpatterns = [
    path('login/', views.login_page, name="login page"),
    path('register/', views.register, name="register page"),
    path('logout/', views.logout_user, name="logout"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('', views.index),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('posts/', include('posts.urls')),
]

mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='test'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='blog'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='post details'),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='post update'),
    path('new_post/', views.new_post, name='new post'),
    path('my_posts/', views.my_posts, name='my posts'),
    path('successful_new_request/', views.successful_new_request, name='successful new post'),
    path('personal_account/', views.personal_account, name='personal account'),
]

mysite/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="keywords" content="инвестиции, деньги, бизнес, тест">
    <meta name="description" content="Портал с ресурсами для обучения инвестированию и проверки своих знаний с помощью теста.">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'common_main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'colors.css' %}">
    {% block links%}{% endblock%}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
</head>
<body>
    <header>
        <p class="logo">WiseInvestor</p>
        <div class="bttns">
            <nav>
                <a href="{% url 'posts:blog' %}">Блог</a>
                <a href="{% url 'polls:test' %}">Тест</a>
                <!--'sources' Источники-->
            </nav>
            <div class="logout">
                <p class="name"><a href="{% url 'allauth:logout' %}">{{request.user}}</a></p>
                <div class="iconSignOut"><i class="fas fa-door-open signOut"></i></div>
            </div>
        </div>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <p>Illustration by <a href="undefined">Natasha Remarchuk</a> from <a href="https://icons8.com/">Icons8</a></p>
    </footer>
</body>
</html>